### ISSUE TITLE
Resource failure

### ISSUE THREAD

**Issue by Corey01327** [nsg-ethz/snowcap#1]
Virtual resources cannot be downloaded anymore. Can you share them from elsewhere? Thank you very much!
Downloaded webpage https://polybox.ethz.ch/index.php/s/pE917fiv5Aiqbd0 , prompt the following content
“File not found.The specified document has not been found on the server.”

**Comment by tiborschneider** [comment]
It seems like the VM image is no longer available. Try to build the program from source. You will be able to reconstruct all the results.

To repeat the case study, you will have to set up GNS3 properly. However, I don't remember how to do that precisely.

Sorry for the bad news. :disappointed:
